// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabPXBWA339MFlPoeRCvY2qUpIRdw_rWQ',
    appId: '1:319988224843:web:20ee286884a365531b8ece',
    messagingSenderId: '319988224843',
    projectId: 'social-hub-project',
    authDomain: 'social-hub-project.firebaseapp.com',
    storageBucket: 'social-hub-project.firebasestorage.app',
    measurementId: 'G-953KPXB8YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR_k_H9VClYg-GSpuo-ehw1Wl4Jzm83rg',
    appId: '1:319988224843:android:67ddc8b8ccdff5a21b8ece',
    messagingSenderId: '319988224843',
    projectId: 'social-hub-project',
    storageBucket: 'social-hub-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr52J5o80TL5W-gBgCLiY020qNfbaHysA',
    appId: '1:319988224843:ios:04af7ad688324dc31b8ece',
    messagingSenderId: '319988224843',
    projectId: 'social-hub-project',
    storageBucket: 'social-hub-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr52J5o80TL5W-gBgCLiY020qNfbaHysA',
    appId: '1:319988224843:ios:04af7ad688324dc31b8ece',
    messagingSenderId: '319988224843',
    projectId: 'social-hub-project',
    storageBucket: 'social-hub-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabPXBWA339MFlPoeRCvY2qUpIRdw_rWQ',
    appId: '1:319988224843:web:d07a4bea39eb31861b8ece',
    messagingSenderId: '319988224843',
    projectId: 'social-hub-project',
    authDomain: 'social-hub-project.firebaseapp.com',
    storageBucket: 'social-hub-project.firebasestorage.app',
    measurementId: 'G-Z5DT8R3YE7',
  );
}
